import Header from "@/components/Header";
import Category from "@/components/Home/Category";
import Product from "@/components/Home/Product";
import Tags from "@/components/Home/Tags";
import { Container } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container maxWidth="md" sx={{ width: "95%" }}>
          <Category />
          <Tags /> 
          <Product />
        </Container>
      </main>
    </>
  );
}
