import { useRouter } from "next/router";
import * as React from "react";
import axios from "@/config/axiosInstance";
import { useAtom } from "jotai";
import { authAtom } from "@/stores/auth";
import { Box, CircularProgress, Container, Typography } from "@mui/material";
import FormCheckout from "@/components/checkout/FormCheckout";
import Head from "next/head";

export default function Checkout() {
  const [auth] = useAtom(authAtom);
  const [loading, setLoading] = React.useState(false);
  const [data, setData] = React.useState<Array<any> | null>(null);

  const getCartItems = React.useCallback(async () => {
    setLoading(true);
    try {
      const response = await axios.get("/api/carts", {
        headers: { Authorization: `Bearer ${auth.token}` },
      });
      setData(response.data.data);
    } catch (error: any) {
      console.log(error?.response);
    } finally {
      setLoading(false);
    }
  }, [auth.token]);

  React.useEffect(() => {
    getCartItems();
    return () => {};
  }, [getCartItems]);

  if (loading) {
    return (
      <Box sx={{ height: "100vh", display: "flex" }}>
        <CircularProgress sx={{ m: "auto" }} />
      </Box>
    );
  }
  

  return (
    <>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth={"md"} sx={{ width: "95%", my: 2 }}>
          <Typography variant="h6">Checkout</Typography>
          <Typography variant="subtitle2">Total items</Typography>
          <Typography variant="h5">{data?.length} items</Typography>
          <Typography variant="h6" sx={{ mt: 2 }}>
            Alamat
          </Typography>
          <FormCheckout disabled={data?.length === 0 ? true : false} />
        </Container>
      </main>
    </>
  );
}
