import Auth from "@/components/auth";
import { Box, Button, Container, Typography } from "@mui/material";
import Head from "next/head";
import * as React from "react";

export default function Account() {
  const [token, setToken] = React.useState<string | null>();

  React.useEffect(() => {
    if (window.localStorage) {
      setToken(window.localStorage.getItem("token"));
    }
  }, [window]);

  if (token === "") {
    return <Auth />;
  }

  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="md" sx={{ width: "95%" }}>
        <Box sx={{mt: 3, display: "flex", justifyContent: "space-between", alignItems:"center"}} >
          <Typography variant={"h5"} sx={{mt: 3}}>Welcome Back</Typography>
          <Button >Logout</Button>
        </Box>
        </Container>
      </main>
    </>
  );
}
