import Login from "@/components/auth/Login";
import Register from "@/components/auth/Register";
import { Box, Button, ButtonGroup } from "@mui/material";
import Head from "next/head";
import Link from "next/link";
import * as React from "react";

export default function Auth() {
  const [index, setIndex] = React.useState(1);
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            width: "100%",
            display: "flex",
            height: "100vh",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Box sx={{ maxWidth: 350, width: "95%" }}>
            <Box
              sx={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}
            >
              <ButtonGroup sx={{ mb: 2 }}>
                <Button
                  onClick={() => setIndex(1)}
                  variant={index === 1 ? "contained" : "outlined"}
                >
                  Login
                </Button>
                <Button
                  onClick={() => setIndex(2)}
                  variant={index !== 1 ? "contained" : "outlined"}
                >
                  Register
                </Button>
              </ButtonGroup>
              <Link href="/" style={{ fontWeight: 600 }}>
                Go to home
              </Link>
            </Box>
            {index === 1 ? <Login /> : <Register setIndex={setIndex} />}
          </Box>
        </Box>
      </main>
    </>
  );
}
